apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: motdsources.motd.alanraison.github.io
spec:
  group: motd.alanraison.github.io
  names:
    kind: MotdSource
    listKind: MotdSourceList
    plural: motdsources
    singular: motdsource
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MotdSource is the Schema for the motdsources API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MotdSourceSpec defines the desired state of MotdSource
          properties:
            hostname:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            port:
              type: integer
            privateKey:
              type: string
            username:
              type: string
          required:
          - hostname
          - port
          - privateKey
          - username
          type: object
        status:
          description: MotdSourceStatus defines the observed state of MotdSource
          properties:
            error:
              type: string
            message:
              type: string
            updated:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              format: date-time
              type: string
          required:
          - message
          - updated
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
